### ISSUE TITLE
MultiServer: `ArchipelagoServer.exe`/`MultiServer.py` takes up 100% CPU when running in background.

### ISSUE THREAD

**Issue by deefdragon** [ArchipelagoMW/Archipelago#2065]
### What happened?

When attempting to run the archipelago server as a background processes using a command like nohup or via a docker container, due to the fact that the archipelago is always expecting input from standard input, some systems will take up an entire CPU core at 100%. 

### What were the expected results?

The ability to execute the ArchipelagoServer with some form of `--headless` flag on the command line to disable constant asking for input from standard input.

### Software

While playing

**Comment by Berserker66** [comment]
WebHost.py is built for that kind of headless operation. input() taking 100% CPU sounds like a bug in your system, rather than the software as well.

**Comment by black-sliver** [comment]
nohup will make input() or readline() raise immediately because stdin does not exist (OSError with `errno=errno.EBADF`).

While nohup is not really supported by AP, I can not reproduce what you are seeing. Could you give steps to reproduce this? For me, on current main, the mentioned OSError will simply terminate the thread that reads from stdin: https://github.com/ArchipelagoMW/Archipelago/blob/f29d5c8cae6f3881dd0c4cd64bd72e1efb8f759f/Utils.py#L471-L485

Letting the console task loop here
https://github.com/ArchipelagoMW/Archipelago/blob/f29d5c8cae6f3881dd0c4cd64bd72e1efb8f759f/MultiServer.py#L2126-L2127 until terminated.
The looping is not nice, but should not cause any major CPU load (could be fixed using Thread.is_alive() in the loop).

**Comment by Berserker66** [comment]
Were unable to reproduce and no response from author.
