### ISSUE TITLE
Bug: can't hint for medallions in OOT

### ISSUE THREAD

**Issue by thislooksfun** [ArchipelagoMW/Archipelago#3247]
### What happened?

When playing a multiworld that includes an OOT game it is impossible to hint on any of the medallions. Trying to hint on a specific medallion (e.g. the Forest Medallion) results in the error "Didn't find something that closely matches 'Forest Medallion', did you mean 'medallions'? (50% sure)"  Following the advice and doing `!hint medallions` results in "Nothing found for recognized item name "medallions". Item appears to not exist in this multiworld."

I know the medallions exist and have specific locations because I can see them in the spoiler log. There just doesn't seem to be a way to check them outside of that.

Additionally (and probably relatedly), collecting medallions does not show in the log, nor does it get sent to any connected text clients, nor does it appear in the tracker.

### What were the expected results?

I would expect to be able to hint on specific medallions (or at least the Forest Medallion, since it gates other checks), or at the very least I expect to be able to hint on where the medallions are at all.

I would also expect that collecting a medallion would appear in the logs / text clients / tracker.

### Software

While playing

**Comment by Onemario1234** [comment]
To be fair, the Medallions can already be hinted at in-game. If you have the option for Maps and Compasses giving dungeon info, the compasses will tell you what Medallion or Spiritual Stone resides at the dungeon the compass is for. If you don't have that option enabled, all the Spiritual Stones and Medallions are hinted via the Temple of Time alter.

The reason these can't be hinted probably has to do with the fact that they can't be shuffled anywhere outside of the dungeon reward spots. Collecting a Medallion or Stone won't show up in the Archipelago logs whatsoever because they aren't Archipelago items.

**Comment by Exempt-Medic** [comment]
This is working as intended
