### ISSUE TITLE
RetroArch support for SM

### ISSUE THREAD

**Issue by Ijwu** [ArchipelagoMW/Archipelago#341]
Referring to PR #340. 

I checked with @Berserker66, admittedly after merging, and it seems that RetroArch cannot read from the ROM itself. Due to the name address being moved in the SNIClient RetroArch will receive commands to read from ROM and will not send back data.

The previous address was intentionally in the RAM because RetroArch can read from RAM.

Any ideas for solutions? Immediate action would be to revert the merged commit until further plan or action is in place, or to revert the SM_ROMNAME_START change but still write to the new location if desired.

@lordlou @strotlog Opinions?

**Comment by Ijwu** [comment]
@Berserker66 let me know we never officially supported RA, but I think it is still worth looking into RetroArch compatibility for SM.

**Comment by strotlog** [comment]
It's a little more complicated than that. But the really simple part is: the old location and the new location from PR #340 are **both in the ROM anyway**, so that made no difference.

Now, to address better RetroArch support, which is not affected by the above change:

RetroArch is able to read the ROM if **both** of the following conditions are met:
- Using RetroArch <= 1.9.0 or RetroArch >= 1.10.1; AND,
- Using a bsnes-mercury core (such as bsnes-mercury-performance)

Thus **RetroArch has sort of always been supported**! I would like to write up some instructions to use it, or someone else can.

The dependency on bsnes-mercury isn't the greatest since it's somewhat awkward to manage cores in RetroArch. bsnes-mercury is also pretty finicky about enabling custom MSU music support for the players that want that. There are at least a few ways to go about removing the dependency on bsnes-mercury:
- In RA: Add support in cores other than bsnes-mercury, such as the RA snes9x-current core, for RA's SET_MEMORY_MAPS API. This enables ROM reads. It's a little bit scary to me because you just pass to RA a read/write buffer pointer with no lifetime specified and no notification when RA writes the buffer owned by the emulator core. jsd1982 was thinking about trying this. OR,
- In AP SM ROM: Copy ROM data to a known location in WRAM or SRAM, first ensuring that no one else wants to write to the chosen location. OR,
- In AP SM ROM: Add a command to the multiworld communication library which enables the ROM's code to accept a read request for a particular address from SNIClient, and read and return ROM data to the SNIClient.

**Comment by strotlog** [comment]
> [MW] never officially supported RA
I suppose I should ask @Berserker66 - beyond some of the technical stuff I described in the above comment, is there any reason RetroArch support couldn't be made official?

**Comment by lordlou** [comment]
I concur with strotlog: SM_ROMNAME_START was never in RAM to start with. I missed that.

**Comment by Berserker66** [comment]
> 

It simply never worked and nobody ever reported it. RA cannot read ROM, only RAM.

**Comment by strotlog** [comment]
OK, neat.

Just to reiterate, RA _can_ read ROM data when the user selects a RA core that implement RA's SET_MEMORY_MAPS API. bsnes-mercury is the only such SNES core that I'm aware of.

Archipelago does support SM in RetroArch today; the biggest limitation is documentation!

Maybe the perception of it not working comes from a previous bug: For a certain period of time (RA 1.92 thru 1.10.0), RA had a problem with the _correctness_ of where it read from within the ROM, when a client requested an address in non-contiguous ROM address space. (99% of the SM ROM is mapped non-contiguously with the beginning of the ROM.) But I tracked that bug down and got it fixed with RA folks in RA 1.10.1.

**Comment by Ijwu** [comment]
According to https://github.com/ArchipelagoMW/Archipelago/pull/365 this seems solved for. Thank you for your contributions, in knowledge and docs, @strotlog. I am closing this issue now.
