### ISSUE TITLE
Port for further architectures?

### ISSUE THREAD

**Issue by UncleKalle** [ArchipelagoMW/Archipelago#3673]
### What feature would you like to see?

Please excuse my lack of knowledge here, but as far as I'm aware, the linux x86 files only run on Intel chips. Are there any plans to port the main program to, for example, ARM devices, so a raspberry pi could run the host application?

**Comment by remyjette** [comment]
https://github.com/ArchipelagoMW/Archipelago/blob/main/docs/running%20from%20source.md

> These steps are for developers or platforms without compiled releases available.

**Comment by black-sliver** [comment]
Just a heads-up if someone digs this up and wants to contribute binary builds for ARM on Linux:
* Github currently does not provide free github-hosted native arm runners for Linux. Hosting runners ourselves (at home or via a cloud provider) is not something we plan to do currently.
* You can totally use qemu in github runners, so that'd be the way to go. Performance is not great though, so we should limit that to `build` and `release` actions.
* Afaict not all arm architectures are supported by the eco system, so maybe limit it to Armv8 and higher? (Raspberry Pi 3 and newer)
* setup.py should work just fine on ARM with the exception of bdist_appimage (and maybe sni, haven't checked), which downloads an amd64 executable
* The most limiting factor as to where you can run the resulting binary is libc, so pick a distribution for qemu that reflects the oldest OS you want to support - for our amd64 builds we currently use ubuntu 20.04, but there has been the idea of switching to something like alma8 or rocky8, which will outlive ubuntu 20.04 for security updates.
