### ISSUE TITLE
Installer 0.3.0 Hotfix 1  - OoT

### ISSUE THREAD

**Issue by Surion79** [ArchipelagoMW/Archipelago#386]
Installer asks for OoT ROM even if i have not selected OoT as Generator Option.  
Can't progress the setup when clicking next.
I do have the OoT Client marked to be installed, and that triggers the mandatory ROM selection. I think that is an issue, otherwise there wouldn't be two options for OoT

**Comment by Ijwu** [comment]
It is not a bug. It is intended that if you select the OoT client then you must have the OoT ROM. The client works by patching your copy of the ROM, and so it must have a version to work on.

The same goes for the generator option as it must have a copy of the ROM in order to generate a patch.

Playing or generating with OoT requires the ROM.

**Comment by Surion79** [comment]
so, all previous versions of the installer had the bug of missing that check? Because I installed the OoT Client without the Generator-Selection and therefore I had no ROM. Last  version I installed in that constellation was 0.2.5

**Comment by Berserker66** [comment]
earlier installers had no OoT client.
