### ISSUE TITLE
Bug: Pokemon Emerald considers Route 121 (balanced for gym 6) a valid place to put items required to get to gym 3

### ISSUE THREAD

**Issue by m4-used-rollout** [ArchipelagoMW/Archipelago#3941]
### What happened?

A tough deadlock:

Player 3 was given an early SS Ticket between gyms 1 and 2. This gave them access to Lilycove and Route 121 (places you don't reach in vanilla until you're at gym 6) as soon as they got to Slateport (after beating gym 2). In order to get to gym 3, you must either have the Letter, or the Dynamo Badge and HM06. The randomizer decided that Player 2's Letter would be in Player 2's game, only reachable after gym 5. Gym 2 gave Player 2 their Dynamo Badge. Player 2's HM06 was placed on Player 3's Route 121 (Item Near Safari Zone).

The spoiler log indicates that the randomizer expected the order of events to go
```
5: {
  Defeat Gym 2 (Player 3): Earn Heat Badge (Badge 4, Player 3)
  Deliver Letter (Player 3)
  Defeat Gym 2 (Player 2): Earn Dynamo Badge (Badge 3, Player 2)
  Deliver Letter (Player 1)
}
6: {
  Post-Letter, Slateport unlocks (Player 1)
  Post-Letter, Slateport unlocks (Player 3)
  Route 121 - Item Near Safari Zone (Player 3): HM06 Rock Smash (Player 2)
}
7: {
  Rescue Captain Stern (Player 1)
  Defeat Gym 3 (Player 2): Earn Mind Badge (Badge 7)
  Team Magma Steals Meteorite (Player 2)
  Route 110 - Itemfinder from Rival (Player 2): Magma Emblem (Player 1)
  Route 113 - Item Past Three Trainers (Player 2): HM08 Dive (Player 1)
  Rescue Captain Stern (Player 3)
}
```
It seems like the randomizer expected Player 3 to jump over to Route 121 right away and grab HM06 for Player 2, and then Player 2 would take the alternate route and actually get out ahead (badge-wise) of Players 1 and 3 for a while while Players 1 and 3 saved Captain Stern.

But in order to get to Route 121 - Item Near Safari Zone, Player 3 has to battle trainers with level 29 Pokemon, after just defeating a gym where the leader's highest Pokemon was level 19. In the base game, you're not intended to go through Route 121 until you're at gym 6, in which you defeat a level 33 Pokemon.

So, Player 3 elected to not go through Route 121 because the trainers were too tough. This meant Player 2 was stuck between gyms 2 and 3 until Player 3 defeated the first 5 gyms and was finally strong enough to attempt Route 121.

### What were the expected results?

Hopefully the randomizer would have taken the trainer levels into account and not considered Route 121 a valid place to put a progression item required so early. We did not set the randomizer to give priority to Route 121. I'm not sure if the randomizer does attempt to take trainer levels into account when it charts progression, but if it doesn't, it probably should. If it does, then it may need more weight.

### Software

While playing

**Comment by Zunawe** [comment]
Would you mind attaching the entire actual spoiler log? Or even just the entire playthrough and everything below it. I know you're trying to make it more readable and concise, but I'm already so familiar with the existing names that it's much easier to read. Even among lots of other players.

In addition, the last section of the spoiler log details exactly what paths the player is expected to take in order to reach a location, so once we nail down which location is wrong, I can see exactly how the generator _thought_ you were supposed to get there.

**Comment by Zunawe** [comment]
Ah, I see, I misunderstood what the report was. Saw the playthrough and assumed it was a report about a bug in the hard logic assumptions.

**Comment by Zunawe** [comment]
The randomizer does not take opponent trainer levels into account. Something like that may be a consideration in the future, but for the moment at least there are other tools available such as a higher XP scaling, matching opponent levels, blind trainers, or (usually) just playing with a more "meta" playstyle of sticking with one high-bst pokemon instead of trying to build a well-rounded team.

Of course, I don't want to make it sound like I'm suggesting the solution is "git gud". Level scaling according to the logic of the seed is planned eventually. But it's not super high priority right now.

**Comment by m4-used-rollout** [comment]
Gotcha. Just pointing out that until level scaling according to the logic is implemented, the randomizer will sometimes expect players to things that require eating a 10 level jump.
