### ISSUE TITLE
General intro-level documentation

### ISSUE THREAD

**Issue by mDuo13** [ArchipelagoMW/Archipelago#567]
- A brief intro to some of the jargon would be helpful. It's not exactly intuitive what people mean when they say "checks" or "location checks" or "in logic" etc.
- The hint system could be a little better documented. It would be even nicer if there was some automatic list of possible hints (e.g. https://archipelago.gg/datapackage ) either in the client or on the website.
- It should be clearer what it means to forfeit—especially the automatic "forfeit" that happens in some games after your goal is completed. It's jarring, for example, when you die on Risk of Rain 2's "Commencement" and get a message saying you "forfeited" but actually you won, basically?
- Games where you don't run a text client should explain how to access the text console or ask for hints

**Comment by alwaysintreble** [comment]
1. I can add this either to one of the setup guides or we could potentially add jargon to the FAQ 
2. if you type `!help` in any of the clients it tells you how to use all of the commands including `!hint` and there is documentation on all of the various client commands already. You can hint for any item that is supported for your game. While it isn't true the working assumption for the randomizers is that the player has played the original game before playing the randomizer. Documenting out every hintable item would be possible but for some games that can be up to 300 items so is not very feasible.
3. forfeit is kind of the name that has just been used for a while and since it can be used for players that haven't necessarily finished changing the name is not probably a good idea at this point. As far as the forced forfeitting on RoR2 the game always does that though I now realize that isn't documented on the site.
4. I agree with you on this point that these should be added to the setup guides for games without a console or a console you can access with a certain key input.

**Comment by Ijwu** [comment]
Will work on this with @alwaysintreble I suppose. May not happen soon as I'm only now coming back to life from a long sleep. :zote:

**Comment by dewiniaid** [comment]
> forfeit is kind of the name that has just been used for a while and since it can be used for players that haven't necessarily finished changing the name is not probably a good idea at this point.

I wouldn't be opposed to a more friendly "I beat the game!" synonym for !forfeit (even if it functionally does the same thing), and the "Soandso has forfeited." messaging being adjusted to not use that language when the game is marked as complete. 

Perhaps !finished and "Soandso has finished their game."?  Ideally a different verb from "Soandso has completed their goal."

**Comment by Berserker66** [comment]
I proposed alternative forfeit names back when collect was added, the general response I got was that it's already called forfeit for so long that people got used to it and that changing it would just result in more confusion. It's now 2 years later..

**Comment by alwaysintreble** [comment]
I support `!finished`, though I'm not sure how the community as a whole would feel about it given manual forfeitting is a thing, even if it is disabled by default, and it'd be a strange interaction in that specific case. I think leaving the admin command `/forfeit <player>` should probably stay so just change the client submitted command. I suppose it could be put to a vote again since the community has changed quite a bit in the last year since `collect` was added when the suggestion was last proposed.

**Comment by Berserker66** [comment]
I think second place back in that day was !release, to go along with !collect (release out your items, collect in your items)

**Comment by ThePhar** [comment]
Could alias `!release` to `!forfeit` as well.

**Comment by alwaysintreble** [comment]
Alright with #680 i believe I've addressed everything mentioned in this post. If there are any that I'm missing still please let me know before I tag this.

**Comment by mDuo13** [comment]
I think this is adequately addressed now that we can close the issue (though of course, there's always room to improve!)
