### ISSUE TITLE
Website: jumping to a section on a page hides the first couple lines

### ISSUE THREAD

**Issue by SoldierofOrder** [ArchipelagoMW/Archipelago#810]
On archipelago.gg, if you follow a link to a specific section on a page, the section header will appear at the very tippy-top of the browser window. However, the very tippy-top of the window is hidden behind the white header bar with all the common links on it, so the first few lines of the section (including the header) are invisible until the user scrolls up. This seems unintentional. Example: ['Joining a multiworld game' on the SC2 setup guide](https://archipelago.gg/tutorial/Starcraft%202%20Wings%20of%20Liberty/setup/en#joining-a-multiworld-game) takes you too low to see all of the instructions.

**Comment by Berserker66** [comment]
can confirm the problem on Vivaldi Browser

**Comment by mDuo13** [comment]
This is because the top of the site uses a "fixed" header, so when the browser scrolls to put the anchor at the very top of the window, it's underneath the header. Very common problem on websites that use fixed headers.

[Here is a page that describes a couple CSS-only solutions](https://calvinke.com/seo/fixed-header-anchor-css/) the site could potentially use to fix this.
